# permissions for end users to view containerinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerinjector-viewer-role
rules:
- apiGroups:
  - apple.dev.thenullchannel
  resources:
  - containerinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apple.dev.thenullchannel
  resources:
  - containerinjectors/status
  verbs:
  - get
